- src/multi-player.js
- src/views/class/multi-player.html
Closes #9 
A static web page has been created for multiplayer mode. 
The modified files include an added multi-player.js file, and code has been added to the multi-player.html file.
Changes include an added 'Start Game' button, and a page heading.
> New page added for multiplayer mode

- src/single-player.js
- src/views/class/single-player.html
Closes #4
A static webpage has been created for the single player mode. The modified files include an added single-player.js file, as well as an edited single-player.html file. A button has been created to start the single player game.
> Player page added for single mode

- src/public/scripts/multi-player.js
- src/public/scripts/single-player-grid.js
- src/public/scripts/single-player.js
- src/views/class/multi-player.html
- src/views/class/single-player-grid.html
- src/views/class/single-player.html
#Closes 6
A 5x6 grid is displayed for both the multi and single player games, when the "start game" button is clicked. The grid will be used as the gameboard where the player can guess the words.
> 6 displaying player grid

- src/index.js
Closes #11 
Changed the port in index.js in order to ensure the website can be hosted on azure.
> Changed port for it to be hosts on azure

- .github/workflows/main_wordz.yml
Fixed the yaml file to look in the src folder when deploying to azure.
> Fixed path for azure deployment

- src/index.js
- src/mainRoutes.js
- src/views/class/rules.html
Closes  #3 
A Rules webpage has been added which explains the rules for single player as well as multiplayer game modes. A modal has been added to this page with rules as well. This is done so that the functionality is there if it is decided to place the modal on different webpages.
> 3 splash screen

- src/mainRoutes.js
- src/public/scripts/login.js
- src/views/class/login.html
A bug was found if no cookies existed when the page was loaded in initially. This has been solved through rewriting git history.
> Solving cookie issue

- src/dictionary.js
- src/mainRoutes.js
- src/public/scripts/single-player.js
Closes #14 
This user story checks if an entered word is valid. If it is valid, the user can continue by entering their word. If it is invalid, the user cannot continue.
> Valid word check

- src/public/scripts/single-player.js
closes #15 
This changes the tile to yellow if the letter is in the answer
> Tile changes to yellow to show that the letter appears in word

- src/public/scripts/single-player.js
closes #16 
Grid Tiles go green when the guessed letter is in the answer and is in the correct position
> tiles go green when the letter is in the word and in the correct position 

- src/public/scripts/single-player.js
Closes #12 
The key on the keyboard changes to green when the player guesses the correct letter in the correct position.
> Succesful letter choice displayed on keyboard

- src/public/scripts/single-player.js
Closes #44 
Keyboard displaying grey when a letter is guessed and does not exist in the word.
> Keys turn green when the correct letter is chosen in the correct place

- src/__test__/dictionary.test.js
- src/__test__/single-player.test.js
- src/package-lock.json
- src/package.json
> Added tests to ensure API requests are working as expected

- src/__test__/database.test.js
- src/db.js
- src/index.js
- src/mainRoutes.js
- src/package-lock.json
- src/package.json
- src/public/scripts/login.js
- src/public/scripts/welcome.js
- src/views/class/index.html
- src/views/class/login.html
Closes #17 
This user story created the database for storing all users. Once a user logs in, the amount of games they have played shows with a welcome message.
> Show the games played after logging in

- src/public/scripts/single-player.js
- src/views/class/single-player.html
Closes #42
The user is notified when they have won or lost with a popup window. The popup can be closed with a button.
> Win or loose popup appears

- src/public/scripts/multi-player.js
- src/views/class/multi-player.html
Closes #25 
This user story adds the single player game functionality to the multiplayer page
> Added single player functionality to the multiplayer page

- src/public/scripts/multi-player.js
- src/public/scripts/single-player.js
Closes #18 
This code adds functionality to redirect the user back to the welcome page once they have one or lost.
Some of the code has been refactored as well to make it more readable.
> Redirected to Welcome after win/loss

- docs/ADRs/ADR2.md
- docs/ADRs/ADR3.md
- src/__test__/database.test.js
- src/mockRoutes.js
Closes #66 
This pull request contains testing for the database. It mocks a database and the commands that would be executed.
> Database testing

- src/code.js
- src/mainRoutes.js
- src/public/scripts/lobby.js
- src/public/scripts/multi-player.js
- src/public/scripts/startRoom.js
- src/views/class/lobby.html
- src/views/class/multi-player.html
- src/views/class/startRoom.html
closes #62 
This story allows for a user to create a game and be redirected to a lobby with a game code. all other users wishing to play this game can enter this code and be redirected to the lobby screen
> Lobby for multiplayer game mode

- src/__test__/codeGen.test.js
- src/__test__/multi-player.test.js
- src/mainRoutes.js
- src/mockRoutes.js
- src/public/scripts/lobby.js
- src/public/scripts/single-player.js
- src/public/scripts/startRoom.js
- src/public/scripts/welcome.js
- src/views/class/startRoom.html
Closes #20 
This user story allows the website to know exactly which user is logged in by storing only the username in local storage
> The website knows the user at all times

- src/__test__/multi-player.test.js
- src/mainRoutes.js
- src/mockRoutes.js
- src/public/scripts/multi-player-random.js
- src/views/class/multi-player-random.html
Closes #23 
This user story colours the opponents' grid on each button click for the multiplayer mode where a word is generated by wordie
> Colour opponent grid in random word gameplay

- src/public/scripts/single-player.js
- src/views/class/single-player.html
Closes #21 
A log of all actions taken by the player (playing in single player mode) shows up in a pop-up window when the game is over. This log includes the following details:
-player's username
-each guess made
-if the guess word was valid/ invalid
-the time and date of the guess made
> Display log of moves at the end of a single player game

- src/public/scripts/single-player.js
Closes #79 
Grids are being colour-coded correctly in both single and multiplayer game modes. The 'delete' functionality has also been fixed so that you cannot delete an already entered guess.
> 79colour codes bug

- src/mainRoutes.js
- src/public/scripts/lobby.js
- src/public/scripts/multi-player-observer.js
- src/public/scripts/multi-player-userSetWord.js
- src/views/class/multi-player-observer.html
- src/views/class/multi-player-userSetWord.html
Closes #61 
Closes #26 
This pull request accidentally deals with two user stories. The grids are colour coded corresponding to the players grids. The observer can watch both player's grids and each player can see eachothers grids.
> 61colour coded grid guess word

- src/public/scripts/multi-player-observer.js
- src/public/scripts/multi-player-random.js
- src/public/scripts/multi-player-userSetWord.js
- src/views/class/multi-player-observer.html
- src/views/class/multi-player-random.html
- src/views/class/multi-player-userSetWord.html
closes #24 
The opponents names have been added above their respective grids.
> 24 opponent name

- src/mainRoutes.js
- src/public/scripts/multi-player-observer.js
- src/public/scripts/multi-player-random.js
- src/public/scripts/multi-player-userSetWord.js
- src/views/class/multi-player-observer.html
- src/views/class/multi-player-random.html
- src/views/class/multi-player-userSetWord.html
Closes #74 
This user story gets logs for all guesses in the mutliplayer game mode. It determines who the winner is and displays the log on all screens
> Multiplayer logs and winners

- src/public/scripts/multi-player-random.js
- src/public/scripts/multi-player-userSetWord.js
- src/public/scripts/single-player.js
Closes #82 
Keyboard functionality has been added for single and multi player games.
> 82 keyboard press
